### PR TITLE
Weeks should start from Sunday

### PR DESCRIPTION
**Pull request by Dafrok**
A week starts from Sunday in general, isn't it? This lib makes weeks start from Saturday at all.

### CODE REVIEW

**Comment by gluons** [comment]
Agree. This lib always start week from **Saturday**. That's really weird.

`2 Dec 2016` and `3 Dec 2016` are the same week. But this lib say that these days are different week. :unamused:

[runkit npm week](https://runkit.com/5844103b0878f00013b43439/5844103b0878f00013b4343a)

---

december 2016 calendar

**Comment by gluons** [comment]
@jonschlinkert Are you here? What's your opinion?

**Comment by jonschlinkert** [comment]
yeah it's obviously wrong, thanks for the reminder. I'll get this merged

**Comment by jonschlinkert** [comment]
published and git tagged as 0.2.0 (this was definitely a bug fix, and might normally warrant a patch, but it's possible this fix will break someone's code). 

thanks!

**Pull request merged**
